-- create table departments(
--      department varchar(100),
--     division varchar(100),
--     primary key (department)
-- );
--
-- create table regions(
--     region_id int,
--     region varchar(20),
--     country varchar(20),
--     primary key (region_id)
-- );
--
--
-- create table employees(
--     employee_id int,
--     first_name varchar(50),
--     last_name varchar(50),
--     email varchar(50),
--     hire_date DATE,
--     department varchar(17),
--     gender varchar(1),
--     salary int,
--     region_id int,
--     primary key (employee_id)
-- );